# Generated by Django 2.1.7 on 2020-03-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
