# Generated by Django 2.1.7 on 2020-03-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('saldo', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
