# Generated by Django 2.1.7 on 2020-03-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('mes', models.DateField(editable=False)),
                ('total_planeado', models.IntegerField()),
                ('total_actual', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
