# Generated by Django 3.0.4 on 2020-04-16 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='tipo',
        ),
    ]
