# Generated by Django 3.0.4 on 2020-04-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_budget_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='estado',
        ),
    ]
